model: a2c
model_name: temp_model         # model filename prefix
load_from_checkpoint: true
total_timesteps: 128         # total training timesteps

paths:
  save_dir: "D:\\Projects\\RL_game\\ue-reinforcement-learning\\PythonEnv\\example_model\\temp_model"
  previous_model: "D:\\Projects\\RL_game\\ue-reinforcement-learning\\PythonEnv\\example_model\\temp_model.zip"

common_parameters:
  device: cpu
  learning_rate: 0.003         # learning rate
  gamma: 0.99                  # discount factor
  verbose: 1                   # 0-no msg / 1-info / 2-debug
  batch_size: 128              # mini-batch size for ppo updates

on_policy:
  n_steps: 1024
  gae_lambda: 0.95
  ent_coef: 0.01

  ppo:
    n_epochs: 10
    clip_range: 0.2
    vf_coef: 0.5

off_policy:
  buffer_size: 1_000_000
  tau: 0.005
  learning_starts: 1000

  sac:
    ent_coef: auto

  td3:
    policy_delay: 2
    target_policy_noise: 0.2
    target_noise_clip: 0.5

  ddpg:
    action_noise: null
