import gymnasium as gym
from typing import Protocol, Callable, Any
from rl_platform.core.specifications import EnvSpec, TaskSpec
import numpy as np
from pathlib import Path


class TrainingCallback(Protocol):
    def on_step(self, step: int, metrics: dict[str, float]) -> bool: ...
    def on_batch_end(self, step: int, metrics: dict[str, float]) -> None: ...
    def on_update_end(self, step: int, metrics: dict[str, float]) -> None: ...
    def on_training_end(self) -> None: ...


class InferencePolicy(Protocol):
    def get_actions(self, obs_batch: np.ndarray) -> np.ndarray: ...

class LearnerPlugin(Protocol):
    def configure(self, env_spec: EnvSpec, config: dict) -> None: ...
    def train(
        self,
        worker_addrs: list[tuple[str, int]] | None,
        env_fns: list[Callable[[], gym.Env]] | None,
        task: TaskSpec | None,
        total_steps: int,
        callbacks: list[TrainingCallback],
    ) -> dict[str, float]: ...
    def load(self, path: Path) -> None: ...
    def save(self, path: Path) -> dict[str, Any]: ...
    def get_policy(self) -> InferencePolicy: ...
